FROM node:20-alpine

WORKDIR /app

# Install backend dependencies
COPY trading-backend/package*.json ./
RUN npm install

# Generate Prisma client
COPY trading-backend/prisma ./prisma/
RUN npx prisma generate

# Copy the rest of the backend source
COPY trading-backend ./

# Expose backend port
EXPOSE 3000

# Start server
CMD ["sh", "-c", "npx prisma db push && npm run start"]
